from app.prompts.templates import (
    GRAPH_EXTRACTION_SYSTEM,
    GRAPH_EXTRACTION_USER,
    PLAYWRIGHT_SYSTEM,
    PLAYWRIGHT_USER,
    TESTCASE_SYSTEM,
    TESTCASE_USER,
)

__all__ = [
    "GRAPH_EXTRACTION_SYSTEM",
    "GRAPH_EXTRACTION_USER",
    "TESTCASE_SYSTEM",
    "TESTCASE_USER",
    "PLAYWRIGHT_SYSTEM",
    "PLAYWRIGHT_USER",
]
